---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Namespace `clickhouse` is created by the keeper base (deployed first) and is where the
# dbt-credentials Secret already lives — so it is intentionally not re-declared here.
resources:
  - cronjob.yaml
  - tester-cronjob.yaml
