---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Note: the 'clickhouse' namespace is created by the keeper base (deployed first),
# so it is intentionally not re-declared here.
resources:
  - clickhouse.yaml
